# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
    - releases/wdio5

variables:
  user: $(BROWSERSTACK_USERNAME)
  key: $(BROWSERSTACK_ACCESS_KEY)

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.16.0'
    checkLatest: false
- task: BrowserStackConfig@0
  inputs:
    BrowserStackServiceEndPoint: 'BrowserStack Connection'
    
- script: npm install
- script: npm list | grep webdriverio
- script: npm test
  displayName: 'Run a one-line script'
- task: BrowserStackResults@0

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
